In [2]:
import re

# 파일 열기
hand = open('mbox-short.txt')

for line in hand:
    line = line.rstrip()  # 오른쪽 공백 제거
    # "From " 으로 시작하고 @가 들어간 줄 찾기
    if re.search('^From .+@', line):
        print(line)

From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
From louis@media.berkeley.edu Fri Jan  4 18:10:48 2008
From zqian@umich.edu Fri Jan  4 16:10:39 2008
From rjlowe@iupui.edu Fri Jan  4 15:46:24 2008
From zqian@umich.edu Fri Jan  4 15:03:18 2008
From rjlowe@iupui.edu Fri Jan  4 14:50:18 2008
From cwen@iupui.edu Fri Jan  4 11:37:30 2008
From cwen@iupui.edu Fri Jan  4 11:35:08 2008
From gsilver@umich.edu Fri Jan  4 11:12:37 2008
From gsilver@umich.edu Fri Jan  4 11:11:52 2008
From zqian@umich.edu Fri Jan  4 11:11:03 2008
From gsilver@umich.edu Fri Jan  4 11:10:22 2008
From wagnermr@iupui.edu Fri Jan  4 10:38:42 2008
From zqian@umich.edu Fri Jan  4 10:17:43 2008
From antranig@caret.cam.ac.uk Fri Jan  4 10:04:14 2008
From gopal.ramasammycook@gmail.com Fri Jan  4 09:05:31 2008
From david.horwitz@uct.ac.za Fri Jan  4 07:02:32 2008
From david.horwitz@uct.ac.za Fri Jan  4 06:08:27 2008
From david.horwitz@uct.ac.za Fri Jan  4 04:49:08 2008
From david.horwitz@uct.ac.za Fri Jan  4 04:33:44 2008
From stephen.marquard@uct.ac.za Fri Jan  4 04:07:34 2008
From louis@media.berkeley.edu Thu Jan  3 19:51:21 2008
From louis@media.berkeley.edu Thu Jan  3 17:18:23 2008
From ray@media.berkeley.edu Thu Jan  3 17:07:00 2008
From cwen@iupui.edu Thu Jan  3 16:34:40 2008
From cwen@iupui.edu Thu Jan  3 16:29:07 2008
From cwen@iupui.edu Thu Jan  3 16:23:48 2008

In [3]:
import re

# 파일 열기
hand = open('mbox-short.txt')

for line in hand:
    line = line.rstrip()  # 오른쪽 공백 제거
    # "From " 으로 시작하고 @가 들어간 줄 찾기
    if re.search('^From:.+@', line):
        print(line)

From: stephen.marquard@uct.ac.za
From: louis@media.berkeley.edu
From: zqian@umich.edu
From: rjlowe@iupui.edu
From: zqian@umich.edu
From: rjlowe@iupui.edu
From: cwen@iupui.edu
From: cwen@iupui.edu
From: gsilver@umich.edu
From: gsilver@umich.edu
From: zqian@umich.edu
From: gsilver@umich.edu
From: wagnermr@iupui.edu
From: zqian@umich.edu
From: antranig@caret.cam.ac.uk
From: gopal.ramasammycook@gmail.com
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: david.horwitz@uct.ac.za
From: stephen.marquard@uct.ac.za
From: louis@media.berkeley.edu
From: louis@media.berkeley.edu
From: ray@media.berkeley.edu
From: cwen@iupui.edu
From: cwen@iupui.edu
From: cwen@iupui.edu

In [4]:
import re

hand = open('mbox-short.txt')
for line in hand:
    line = line.rstrip()
    # 이메일 패턴에 맞는 부분을 모두 찾아서 리스트로 반환
    x = re.findall('[a-zA-Z0-9]\S+@\S+[a-zA-Z]', line)
    if len(x) > 0:
        print(x)

['stephen.marquard@uct.ac.za']
['postmaster@collab.sakaiproject.org']
['200801051412.m05ECIaH010327@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['stephen.marquard@uct.ac.za']
['source@collab.sakaiproject.org']
['stephen.marquard@uct.ac.za']
['stephen.marquard@uct.ac.za']
['louis@media.berkeley.edu']
['postmaster@collab.sakaiproject.org']
['200801042308.m04N8v6O008125@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['louis@media.berkeley.edu']
['source@collab.sakaiproject.org']
['louis@media.berkeley.edu']
['louis@media.berkeley.edu']
['zqian@umich.edu']
['postmaster@collab.sakaiproject.org']
['200801042109.m04L92hb007923@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['zqian@umich.edu']
['source@collab.sakaiproject.org']
['zqian@umich.edu']
['zqian@umich.edu']
['rjlowe@iupui.edu']
['postmaster@collab.sakaiproject.org']
['200801042044.m04Kiem3007881@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['rjlowe@iupui.edu']
['source@collab.sakaiproject.org']
['rjlowe@iupui.edu']
['rjlowe@iupui.edu']
['zqian@umich.edu']
['postmaster@collab.sakaiproject.org']
['200801042001.m04K1cO0007738@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['zqian@umich.edu']
['source@collab.sakaiproject.org']
['zqian@umich.edu']
['zqian@umich.edu']
['zqian@umich.edu']
['rjlowe@iupui.edu']
['postmaster@collab.sakaiproject.org']
['200801041948.m04JmdwO007705@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['rjlowe@iupui.edu']
['source@collab.sakaiproject.org']
['rjlowe@iupui.edu']
['rjlowe@iupui.edu']
['cwen@iupui.edu']
['postmaster@collab.sakaiproject.org']
['200801041635.m04GZQGZ007313@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['cwen@iupui.edu']
['hu2@iupui.edu']
['cwen@iupui.edu']
['postmaster@collab.sakaiproject.org']
['200801041633.m04GX6eG007292@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['cwen@iupui.edu']
['hu2@iupui.edu']
['gsilver@umich.edu']
['postmaster@collab.sakaiproject.org']
['200801041611.m04GB1Lb007221@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['gsilver@umich.edu']
['source@collab.sakaiproject.org']
['gsilver@umich.edu']
['gsilver@umich.edu']
['gsilver@umich.edu']
['postmaster@collab.sakaiproject.org']
['200801041610.m04GA5KP007209@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['gsilver@umich.edu']
['source@collab.sakaiproject.org']
['gsilver@umich.edu']
['gsilver@umich.edu']
['zqian@umich.edu']
['postmaster@collab.sakaiproject.org']
['200801041609.m04G9EuX007197@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['zqian@umich.edu']
['source@collab.sakaiproject.org']
['zqian@umich.edu']
['zqian@umich.edu']
['gsilver@umich.edu']
['postmaster@collab.sakaiproject.org']
['200801041608.m04G8d7w007184@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['gsilver@umich.edu']
['source@collab.sakaiproject.org']
['gsilver@umich.edu']
['gsilver@umich.edu']
['wagnermr@iupui.edu']
['postmaster@collab.sakaiproject.org']
['200801041537.m04Fb6Ci007092@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['wagnermr@iupui.edu']
['source@collab.sakaiproject.org']
['wagnermr@iupui.edu']
['wagnermr@iupui.edu']
['zqian@umich.edu']
['postmaster@collab.sakaiproject.org']
['200801041515.m04FFv42007050@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['zqian@umich.edu']
['source@collab.sakaiproject.org']
['zqian@umich.edu']
['zqian@umich.edu']
['antranig@caret.cam.ac.uk']
['postmaster@collab.sakaiproject.org']
['200801041502.m04F21Jo007031@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['antranig@caret.cam.ac.uk']
['source@collab.sakaiproject.org']
['antranig@caret.cam.ac.uk']
['antranig@caret.cam.ac.uk']
['gopal.ramasammycook@gmail.com']
['postmaster@collab.sakaiproject.org']
['200801041403.m04E3psW006926@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['gopal.ramasammycook@gmail.com']
['source@collab.sakaiproject.org']
['gopal.ramasammycook@gmail.com']
['gopal.ramasammycook@gmail.com']
['david.horwitz@uct.ac.za']
['postmaster@collab.sakaiproject.org']
['200801041200.m04C0gfK006793@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['david.horwitz@uct.ac.za']
['source@collab.sakaiproject.org']
['david.horwitz@uct.ac.za']
['david.horwitz@uct.ac.za']
['david.horwitz@uct.ac.za']
['dhorwitz@david-horwitz-6:~/branchManagemnt/sakai_2-5-x']
['dhorwitz@david-horwitz-6:~/branchManagemnt/sakai_2-5-x']
['david.horwitz@uct.ac.za']
['postmaster@collab.sakaiproject.org']
['200801041106.m04B6lK3006677@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['david.horwitz@uct.ac.za']
['source@collab.sakaiproject.org']
['david.horwitz@uct.ac.za']
['david.horwitz@uct.ac.za']
['david.horwitz@uct.ac.za']
['postmaster@collab.sakaiproject.org']
['200801040947.m049lUxo006517@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['david.horwitz@uct.ac.za']
['source@collab.sakaiproject.org']
['david.horwitz@uct.ac.za']
['david.horwitz@uct.ac.za']
['josrodri@iupui.edu']
['dhorwitz@david-horwitz-6:~/branchManagemnt/sakai_2-5-x']
['david.horwitz@uct.ac.za']
['postmaster@collab.sakaiproject.org']
['200801040932.m049W2i5006493@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['david.horwitz@uct.ac.za']
['source@collab.sakaiproject.org']
['david.horwitz@uct.ac.za']
['david.horwitz@uct.ac.za']
['josrodri@iupui.edu']
['dhorwitz@david-horwitz-6:~/branchManagemnt/sakai_2-5-x']
['stephen.marquard@uct.ac.za']
['postmaster@collab.sakaiproject.org']
['200801040905.m0495rWB006420@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['stephen.marquard@uct.ac.za']
['source@collab.sakaiproject.org']
['stephen.marquard@uct.ac.za']
['stephen.marquard@uct.ac.za']
['louis@media.berkeley.edu']
['postmaster@collab.sakaiproject.org']
['200801040023.m040NpCc005473@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['louis@media.berkeley.edu']
['source@collab.sakaiproject.org']
['louis@media.berkeley.edu']
['louis@media.berkeley.edu']
['louis@media.berkeley.edu']
['postmaster@collab.sakaiproject.org']
['200801032216.m03MGhDa005292@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['louis@media.berkeley.edu']
['source@collab.sakaiproject.org']
['louis@media.berkeley.edu']
['louis@media.berkeley.edu']
['ray@media.berkeley.edu']
['postmaster@collab.sakaiproject.org']
['200801032205.m03M5Ea7005273@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['ray@media.berkeley.edu']
['source@collab.sakaiproject.org']
['ray@media.berkeley.edu']
['ray@media.berkeley.edu']
['cwen@iupui.edu']
['postmaster@collab.sakaiproject.org']
['200801032133.m03LX3gG005191@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['cwen@iupui.edu']
['cwen@iupui.edu']
['postmaster@collab.sakaiproject.org']
['200801032127.m03LRUqH005177@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['cwen@iupui.edu']
['wagnermr@iupui.edu']
['cwen@iupui.edu']
['postmaster@collab.sakaiproject.org']
['200801032122.m03LMFo4005148@nakamura.uits.iupui.edu']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['source@collab.sakaiproject.org']
['apache@localhost']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['source@collab.sakaiproject.org']
['cwen@iupui.edu']
['cwen@iupui.edu']
['wagnermr@iupui.edu']

<>:7: SyntaxWarning: invalid escape sequence '\S'
<>:7: SyntaxWarning: invalid escape sequence '\S'
/tmp/ipython-input-2927529464.py:7: SyntaxWarning: invalid escape sequence '\S'
  x = re.findall('[a-zA-Z0-9]\S+@\S+[a-zA-Z]', line)

In [6]:
emails = set()
hand = open('mbox-short.txt')
for line in hand:
    line = line.rstrip()
    x = re.findall(r'[a-zA-Z0-9]\S+@\S+[a-zA-Z]', line)
    for mail in x:
        emails.add(mail)

for mail in sorted(emails):
    print(mail)

200801032122.m03LMFo4005148@nakamura.uits.iupui.edu
200801032127.m03LRUqH005177@nakamura.uits.iupui.edu
200801032133.m03LX3gG005191@nakamura.uits.iupui.edu
200801032205.m03M5Ea7005273@nakamura.uits.iupui.edu
200801032216.m03MGhDa005292@nakamura.uits.iupui.edu
200801040023.m040NpCc005473@nakamura.uits.iupui.edu
200801040905.m0495rWB006420@nakamura.uits.iupui.edu
200801040932.m049W2i5006493@nakamura.uits.iupui.edu
200801040947.m049lUxo006517@nakamura.uits.iupui.edu
200801041106.m04B6lK3006677@nakamura.uits.iupui.edu
200801041200.m04C0gfK006793@nakamura.uits.iupui.edu
200801041403.m04E3psW006926@nakamura.uits.iupui.edu
200801041502.m04F21Jo007031@nakamura.uits.iupui.edu
200801041515.m04FFv42007050@nakamura.uits.iupui.edu
200801041537.m04Fb6Ci007092@nakamura.uits.iupui.edu
200801041608.m04G8d7w007184@nakamura.uits.iupui.edu
200801041609.m04G9EuX007197@nakamura.uits.iupui.edu
200801041610.m04GA5KP007209@nakamura.uits.iupui.edu
200801041611.m04GB1Lb007221@nakamura.uits.iupui.edu
200801041633.m04GX6eG007292@nakamura.uits.iupui.edu
200801041635.m04GZQGZ007313@nakamura.uits.iupui.edu
200801041948.m04JmdwO007705@nakamura.uits.iupui.edu
200801042001.m04K1cO0007738@nakamura.uits.iupui.edu
200801042044.m04Kiem3007881@nakamura.uits.iupui.edu
200801042109.m04L92hb007923@nakamura.uits.iupui.edu
200801042308.m04N8v6O008125@nakamura.uits.iupui.edu
200801051412.m05ECIaH010327@nakamura.uits.iupui.edu
antranig@caret.cam.ac.uk
apache@localhost
cwen@iupui.edu
david.horwitz@uct.ac.za
dhorwitz@david-horwitz-6:~/branchManagemnt/sakai_2-5-x
gopal.ramasammycook@gmail.com
gsilver@umich.edu
hu2@iupui.edu
josrodri@iupui.edu
louis@media.berkeley.edu
postmaster@collab.sakaiproject.org
ray@media.berkeley.edu
rjlowe@iupui.edu
source@collab.sakaiproject.org
stephen.marquard@uct.ac.za
wagnermr@iupui.edu
zqian@umich.edu

In [10]:
import re

hand = open('mbox-short.txt')
for line in hand:
    line = line.rstrip()
    # X-... 으로 시작하는 줄에서 콜론(:) 뒤에 오는 숫자(소수 포함)를 추출
    x = re.findall(r'^X\S*: ([0-9.]+)', line)
    if len(x) > 0:
        print(x)

['0.8475']
['0.0000']
['0.6178']
['0.0000']
['0.6961']
['0.0000']
['0.7565']
['0.0000']
['0.7626']
['0.0000']
['0.7556']
['0.0000']
['0.7002']
['0.0000']
['0.7615']
['0.0000']
['0.7601']
['0.0000']
['0.7605']
['0.0000']
['0.6959']
['0.0000']
['0.7606']
['0.0000']
['0.7559']
['0.0000']
['0.7605']
['0.0000']
['0.6932']
['0.0000']
['0.7558']
['0.0000']
['0.6526']
['0.0000']
['0.6948']
['0.0000']
['0.6528']
['0.0000']
['0.7002']
['0.0000']
['0.7554']
['0.0000']
['0.6956']
['0.0000']
['0.6959']
['0.0000']
['0.7556']
['0.0000']
['0.9846']
['0.0000']
['0.8509']
['0.0000']
['0.9907']
['0.0000']

In [15]:
import re

hand = open('mbox-short.txt')
for line in hand:
    line = line.rstrip()
    # "Details: rev=" 으로 시작하는 줄에서 숫자(점 포함)를 추출
    x = re.findall('^Details:rev', line)
    if len(x) > 0:
        print(x)

In [16]:
import re

emails = [
    "nick@example.com",
    "nora@hanmail.net",
    "steve@gmail.com",
    "nancy.kim@naver.com"
]

pattern = re.compile(r'^n\S*@([A-Za-z0-9.-]+\.[A-Za-z]+)')

for mail in emails:
    m = pattern.match(mail)
    if m:
        print("이메일:", mail, "→ 도메인:", m.group(1))

이메일: nick@example.com → 도메인: example.com
이메일: nora@hanmail.net → 도메인: hanmail.net
이메일: nancy.kim@naver.com → 도메인: naver.com

In [17]:
import re
p = re.compile('[a-z]+')   # 소문자 알파벳(a~z)이 1개 이상 연속되는 패턴

m = p.match("python")      # 문자열의 시작부터 이 패턴이 매칭되는지 확인
print(m)


m = p.match("3python")
print(m)   # None (시작이 숫자라 매칭 실패)

m = p.search("3python")
print(m)   # <re.Match object; span=(1, 7), match='python'>

<re.Match object; span=(0, 6), match='python'>
None
<re.Match object; span=(1, 7), match='python'>

In [19]:
import re
p = re.compile('[a-z]+')
result = p.findall("life is too short")
print(result)

import re

p = re.compile('[a-z]+')

text = "life is too short"

for m in p.finditer(text):
    print(m, "→", m.group(), "위치:", m.span())

['life', 'is', 'too', 'short']
<re.Match object; span=(0, 4), match='life'> → life 위치: (0, 4)
<re.Match object; span=(5, 7), match='is'> → is 위치: (5, 7)
<re.Match object; span=(8, 11), match='too'> → too 위치: (8, 11)
<re.Match object; span=(12, 17), match='short'> → short 위치: (12, 17)

In [23]:
import re

p = re.compile('[a-z]+')
text = "life is too short"
pp=p.finditer(text)
for m in pp:
    print("매칭된 문자열:", m.group(), "→ 위치:", m.span())
for m in pp: # 휘발성 데이터의 특징
    print("매칭된 문자열:", m.group(), "→ 위치:", m.span())

매칭된 문자열: life → 위치: (0, 4)
매칭된 문자열: is → 위치: (5, 7)
매칭된 문자열: too → 위치: (8, 11)
매칭된 문자열: short → 위치: (12, 17)

In [25]:
import pandas as pd

boston_url = 'https://andybek.com/pandas-marathon'
boston = pd.read_csv(boston_url)
boston.info()
boston.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           1000 non-null   object
 1   Age            1000 non-null   int64
 2   M/F            1000 non-null   object
 3   City           1000 non-null   object
 4   State          807 non-null    object
 5   Country        1000 non-null   object
 6   Official Time  1000 non-null   object
 7   Overall        1000 non-null   int64
 8   Gender         1000 non-null   int64
 9   Years Ran      315 non-null    object
dtypes: int64(3), object(7)
memory usage: 78.3+ KB

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran
0,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,2:09:37,1,1,NaN
1,"Rupp, Galen",30,M,Portland,OR,USA,2:09:58,2,2,NaN
2,"Osako, Suguru",25,M,Machida-City,NaN,JPN,2:10:28,3,3,NaN
3,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,2:12:08,4,4,NaN
4,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,2:12:35,5,5,2015

In [29]:
boston.City.str.upper()       # 모두 대문자
boston.City.str.lower()       # 모두 소문자
boston.City.str.swapcase()    # 대↔소문자 뒤집기
boston.City.str.capitalize()  # 첫 글자만 대문자

0           Keringet
1           Portland
2       Machida-city
3      Mammoth lakes
4           Marakwet
           ...
995    North andover
996          Raleigh
997        Arlington
998          Danbury
999         Santa fe
Name: City, Length: 1000, dtype: object

In [34]:
boston.Name.iloc[0:2].str.strip()
boston.Name.str.split(', ')
boston.Name.str.split(', ').str.get(1)   # 이름 (John)
boston.Name.str.split(', ').str.get(0)   # 성 (Smith)

0           Kirui
1            Rupp
2           Osako
3          Biwott
4          Chebet
          ...
995        Larosa
996    Williamson
997         Mccue
998        Larosa
999       Sanchez
Name: Name, Length: 1000, dtype: object

In [35]:
boston['First Name'] = boston.Name.str.split(', ').str.get(1)
boston['Last Name'] = boston.Name.str.split(', ').str.get(0)

In [36]:
boston['M/F'].str.cat(boston.Age.astype(str), sep='_')

0      M_24
1      M_30
2      M_25
3      M_32
4      M_31
       ...
995    M_38
996    M_43
997    M_40
998    M_35
999    M_35
Name: M/F, Length: 1000, dtype: object

In [37]:
boston.Country.str.slice(0, 2, 1)

0      KE
1      US
2      JP
3      US
4      KE
       ..
995    US
996    US
997    US
998    US
999    US
Name: Country, Length: 1000, dtype: object

In [38]:
boston.Country.str.slice(start=-2, step=1, stop=None)

0      EN
1      SA
2      PN
3      SA
4      EN
       ..
995    SA
996    SA
997    SA
998    SA
999    SA
Name: Country, Length: 1000, dtype: object

In [39]:
boston.Country.str.match('ITA')

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Country, Length: 1000, dtype: bool

In [40]:
boston[boston.Country.str.match('ITA')]

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran,First Name,Last Name
56,"Boudalia, Said Sr.",48,M,Belluno,NaN,ITA,2:30:11,57,51,2015:2016,Said Sr.,Boudalia
156,"Achmuller, Hermann",46,M,Brixen,NaN,ITA,2:38:40,157,139,NaN,Hermann,Achmuller
792,"Consolandi, Paolo Giorgio",39,M,Pessano Con Bornago (mi),NaN,ITA,2:53:29,793,747,NaN,Paolo Giorgio,Consolandi
922,"Zompanti, Alessandro",48,M,Fiuggi Fr,NaN,ITA,2:55:12,923,872,NaN,Alessandro,Zompanti

In [43]:
wills = boston.Name.str.contains('Will')
boston[wills]

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran,First Name,Last Name
93,"Vanos, William",45,M,Orlando,FL,USA,2:34:40,94,84,NaN,William,Vanos
199,"Guzick, William F",28,M,Boston,MA,USA,2:40:43,200,178,NaN,William F,Guzick
415,"Hartje, William",24,M,Neptune Beach,FL,USA,2:46:56,416,386,NaN,William,Hartje
429,"Adams, William C",33,M,Arlington,VA,USA,2:47:15,430,399,NaN,William C,Adams
456,"Cunha, Will",28,M,Pittsburgh,PA,USA,2:47:39,457,424,NaN,Will,Cunha
526,"Swenson, Will",45,M,Andover,MA,USA,2:49:10,527,490,2015:2016,Will,Swenson
571,"Gates, William E. Jr.",27,M,Maryville,TN,USA,2:49:44,572,534,NaN,William E. Jr.,Gates
711,"Swanson, William G",32,M,Riverside,CA,USA,2:52:16,712,670,NaN,William G,Swanson
814,"Williamson, David",49,M,Sutton,NaN,GBR,2:53:46,815,768,NaN,David,Williamson
835,"Vargas, Will",42,M,Bogota,NaN,COL,2:54:07,836,789,2016,Will,Vargas
892,"Rivera, Will",46,M,Elizabethtown,KY,USA,2:54:53,893,843,NaN,Will,Rivera
897,"Feldman, William P.",31,M,Greensboro,NC,USA,2:54:56,898,848,NaN,William P.,Feldman
936,"Decamps, William M.",30,M,Atlanta,GA,USA,2:55:22,937,886,NaN,William M.,Decamps
939,"Versen, William R",25,M,Minneapolis,MN,USA,2:55:24,940,889,NaN,William R,Versen
996,"Williamson, Jerry A",43,M,Raleigh,NC,USA,2:56:06,997,941,2015,Jerry A,Williamson

In [44]:
boston.Name.str.contains('will', case=False)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996     True
997    False
998    False
999    False
Name: Name, Length: 1000, dtype: bool

In [45]:
boston.Name.str.contains(r'^Will')   # Will로 시작하는 이름만

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996     True
997    False
998    False
999    False
Name: Name, Length: 1000, dtype: bool

In [46]:
boston.Name[boston.Name.str.contains('Will')]

93            Vanos, William
199        Guzick, William F
415          Hartje, William
429         Adams, William C
456              Cunha, Will
526            Swenson, Will
571    Gates, William E. Jr.
711       Swanson, William G
814        Williamson, David
835             Vargas, Will
892             Rivera, Will
897      Feldman, William P.
936      Decamps, William M.
939        Versen, William R
996      Williamson, Jerry A
Name: Name, dtype: object

In [47]:
boston.Name[boston.Name.str.contains(r'[wW]ill', regex=True)]

93            Vanos, William
199        Guzick, William F
415          Hartje, William
429         Adams, William C
456              Cunha, Will
526            Swenson, Will
571    Gates, William E. Jr.
711       Swanson, William G
814        Williamson, David
835             Vargas, Will
892             Rivera, Will
897      Feldman, William P.
936      Decamps, William M.
939        Versen, William R
996      Williamson, Jerry A
Name: Name, dtype: object

In [48]:
boston.Name[boston.Name.str.contains(r',\s[wW]ill$', regex=True)]

456      Cunha, Will
526    Swenson, Will
835     Vargas, Will
892     Rivera, Will
Name: Name, dtype: object

In [49]:
boston['Official Time'].head()

0    2:09:37
1    2:09:58
2    2:10:28
3    2:12:08
4    2:12:35
Name: Official Time, dtype: object

In [50]:
boston['Official Time'].str.replace(
    r'(\d+):(\d+):(\d+)',
    r'\1 hours, \2 minutes, and \3 seconds',
    regex=True
)

0      2 hours, 09 minutes, and 37 seconds
1      2 hours, 09 minutes, and 58 seconds
2      2 hours, 10 minutes, and 28 seconds
3      2 hours, 12 minutes, and 08 seconds
4      2 hours, 12 minutes, and 35 seconds
                      ...
995    2 hours, 56 minutes, and 06 seconds
996    2 hours, 56 minutes, and 06 seconds
997    2 hours, 56 minutes, and 06 seconds
998    2 hours, 56 minutes, and 07 seconds
999    2 hours, 56 minutes, and 08 seconds
Name: Official Time, Length: 1000, dtype: object

In [51]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = """<data>
<country name="Liechtenstein">
  <rank>1</rank>
  <year>2008</year>
  <gdppc>141100</gdppc>
  <neighbor name="Austria" direction="E"/>
  <neighbor name="Switzerland" direction="W"/>
</country>
<country name="Singapore">
  <rank>4</rank>
  <year>2011</year>
  <gdppc>59900</gdppc>
  <neighbor name="Malaysia" direction="N"/>
</country>
<country name="Panama">
  <rank>68</rank>
  <year>2011</year>
  <gdppc>13600</gdppc>
  <neighbor name="Costa Rica" direction="W"/>
  <neighbor name="Colombia" direction="E"/>
</country>
</data>"""

# XML 파싱
root = ET.fromstring(xml_data)

rows = []
for c in root.findall("country"):
    row = {
        "country": c.attrib["name"],
        "rank": c.find("rank").text,
        "year": c.find("year").text,
        "gdppc": c.find("gdppc").text,
        # neighbor는 여러 개일 수 있으므로 join
        "neighbors": ", ".join([n.attrib["name"] for n in c.findall("neighbor")])
    }
    rows.append(row)

df = pd.DataFrame(rows)
print(df)

         country rank  year   gdppc             neighbors
0  Liechtenstein    1  2008  141100  Austria, Switzerland
1      Singapore    4  2011   59900              Malaysia
2         Panama   68  2011   13600  Costa Rica, Colombia

In [52]:
import xml.etree.ElementTree as ET

# XML 파일 파싱
tree = ET.parse('country_data.xml')
root = tree.getroot()

print(root.tag)       # 최상위 태그 이름 출력 (예: "data")
print(root.attrib)    # 최상위 태그의 속성 딕셔너리 출력 (여기서는 {})

# root의 바로 아래 자식 노드 출력
for child in root:
    print(child.tag, child.attrib)

# root[0] : 첫 번째 <country>
# root[0][1] : 그 안의 두 번째 자식 태그 (<year>)
print(root[0][1].text)  # <year> 태그 안의 값 출력

data
{}
country {'name': 'Liechtenstein'}
country {'name': 'Singapore'}
country {'name': 'Panama'}
2008

In [53]:
for neighbor in root.iter('neighbor'):
    print(neighbor.attrib)

{'name': 'Austria', 'direction': 'E'}
{'name': 'Switzerland', 'direction': 'W'}
{'name': 'Malaysia', 'direction': 'N'}
{'name': 'Costa Rica', 'direction': 'W'}
{'name': 'Colombia', 'direction': 'E'}

In [54]:
for country in root.findall('country'):
    rank = country.find('rank').text
    name = country.get('name')
    print(name, rank)

Liechtenstein 1
Singapore 4
Panama 68